server:
  servlet:
    context-path: /myboot
  port: 8081
spring:
  thymeleaf:
     cache: false
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/sqltest?userUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: f745056231p
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false
mybatis:
  #config-location: classpath:mybatis-config.xml
  #配置mapper.xml的映射路径
  mapper-locations: classpath:com/javasm/springbootdemo/*/mapper/*.xml




#logging:
#  level: {root:debug}
#  path: D:/logs/
#  file: logs/test.log

